/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLoading: typeof import('./src/components/common/app-loading.vue')['default']
    BetterScroll: typeof import('./src/components/custom/better-scroll.vue')['default']
    CountTo: typeof import('./src/components/custom/count-to.vue')['default']
    DarkModeContainer: typeof import('./src/components/common/dark-mode-container.vue')['default']
    DarkModeSwitch: typeof import('./src/components/common/dark-mode-switch.vue')['default']
    ExceptionBase: typeof import('./src/components/common/exception-base.vue')['default']
    GithubLink: typeof import('./src/components/custom/github-link.vue')['default']
    HoverContainer: typeof import('./src/components/common/hover-container.vue')['default']
    IconSelect: typeof import('./src/components/custom/icon-select.vue')['default']
    ImageVerify: typeof import('./src/components/custom/image-verify.vue')['default']
    LoadingEmptyWrapper: typeof import('./src/components/business/loading-empty-wrapper.vue')['default']
    LoginAgreement: typeof import('./src/components/business/login-agreement.vue')['default']
    NaiveProvider: typeof import('./src/components/common/naive-provider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/custom/svg-icon.vue')['default']
    SystemLogo: typeof import('./src/components/common/system-logo.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    WebSiteLink: typeof import('./src/components/custom/web-site-link.vue')['default']
  }
}
